server:
  port: 8282

spring:
  data:
    mongodb:
      uri: ${US_MONGODB_URI}
      database: ${US_MONGODB_DB}
      username: ${US_MONGODB_USERNAME}
      password: ${US_MONGODB_PASSWORD}
      authentication-database: admin

deployment:
  ip:
    ui:
      local: http://localhost:4200
      deployed: https://urartusoftware.com

cloudinary:
  cloud-name: ${US_CLOUDINARY_NAME}
  api:
    key: ${US_CLOUDINARY_API_KEY}
    secret: ${US_CLOUDINARY_API_SECRET}
